_base_: "default.yml"
defaults:
  - _self_

seed: 0
model_name: CLIP_DINOiser
model:
  type: CLIP_DINOiser
  clip_backbone: maskclip
  vit_arch: vit_base
  vit_patch_size: 16
  enc_type_feats: "v"
  gamma: 0.2
  in_dim: 256
  delta: 0.99
  feats_idx: -3

train:
  batch_size: 16
  corr_lr: 0.00005
  found_lr: 0.01
  num_workers: 4
  epochs: 100
  milestones:
    - 5000
  step_lr_gamma: 0.1
  data: "/home/data/imagenet" # CHANGE to your ImageNet data folder
  loss: CE
  ds_size: 1000
  im_size: 448
output: "" # CHANGE to your results folder

evaluate:
  eval_only: true
  task:
    - voc
    # - context
    # - coco_object
    # - context59
    # - voc20
    # - coco_stuff
    # - cityscapes
    # - ade20k

  # evaluation
  voc: src/evaluations/segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: src/evaluations/segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: src/evaluations/segmentation/configs/_base_/datasets/pascal_context.py
  context59: src/evaluations/segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: src/evaluations/segmentation/configs/_base_/datasets/stuff.py
  coco_object: src/evaluations/segmentation/configs/_base_/datasets/coco.py
  cityscapes: src/evaluations/segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: src/evaluations/segmentation/configs/_base_/datasets/ade20k.py
