_base_: "default.yml"
defaults:
  - _self_

seed: 0
model_name: ours
model:
  type: OursCLIPInference
  embed_dim: 768
  use_templates: true

output: ""

evaluate:
  eval_only: true

  task:
    - voc # OK with .tar
    - voc20 # OK with .tar
    - ade20k # OK with .tar
    - context # OK with .tar
    - coco_object # OK with .tar
    - context59  # OK with .tar
    - coco_stuff # OK with .tar
    - cityscapes # OK with .tar

  # evaluation
  voc: src/evaluations/segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: src/evaluations/segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: src/evaluations/segmentation/configs/_base_/datasets/pascal_context.py
  context59: src/evaluations/segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: src/evaluations/segmentation/configs/_base_/datasets/stuff.py
  coco_object: src/evaluations/segmentation/configs/_base_/datasets/coco.py
  cityscapes: src/evaluations/segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: src/evaluations/segmentation/configs/_base_/datasets/ade20k.py

